### ISSUE TITLE
Multiple

### ISSUE THREAD

**Issue by E7t7t7** [MOj0/LoR-Bot#29] opened 2023-08-16 05:58 UTC
Instructions were followed exactly and yet the mana issue still happens randomly.

second after a game ends the bot will randomly not understand that it has ended and get stuck in the screen with the play button visible but not continue

Mojo added on discord - pengy

**Comment by MOj0** [comment] 2023-08-16 07:06
Hmm, are you sure you setup everything? It works for me with this setup:

- Game running full-screen at 1920x1080 resolution
- At least medium quality,
- Windows display scaling set to 100%
- In-game third party endpoints enabled on port 21337 (should be on by default)

If it still does not work take a look at some of the previous issues, [this](https://github.com/MOj0/LoR-Bot/issues/22) for example.

Now the second problem where it gets stuck on the menu is quite strange, since it does not use any screen recognition there. Can you add some `print` statements to display the state of the `StateMachine` and send it here?

**Comment by E7t7t7** [comment] 2023-08-16 17:04
i changed my monitor resolution to 1920x1080 and put it to full screen on ulti detail scaling is 100 and yes the end points are the same.

i followed that thread and nothing work hence me putting my resolution of my monitor to 1920x1080 to avoid any issues

also how do you do the print statements

**Comment by E7t7t7** [comment] 2023-08-16 17:06
https://gyazo.com/d02cafb028dc943e95bbf45f71b58ca4

**Comment by E7t7t7** [comment] 2023-08-16 17:07
https://gyazo.com/d02cafb028dc943e95bbf45f71b58ca4

when bot is running i have that full screen button on but i turned off for screenshot

https://gyazo.com/f8fc9fcc14d39ae198cfd4039509937a

**Comment by MOj0** [comment] 2023-08-16 17:38
The problem is your game is not running fullscreen. That would explain the unknown mana. In the issue I've linked, the guy had the same problem and he solved it by setting the window to borderless. Perhaps that could work here as well.
Also for screenshots you can simply paste them into Github and it will upload them.
Also also, you can print something to the console by writing `print` in Python. If you search for print in the code you will see many examples :)

**Comment by E7t7t7** [comment] 2023-08-16 20:14
the game is fullscreen when the bot is running. i only turned fullscreen off when i took the screenshots to show you my settings

**Comment by E7t7t7** [comment] 2023-08-16 20:14
should i have it borderless even if it is fullscreened anyway? seems redundant

**Comment by MOj0** [comment] 2023-08-16 21:02
Oh I see, if the game is fullscreen while the bot is running that's ok. The thing is, if it is set to windowed, it has a title bar which is about 40 pixels high. This then messes up the screen recognition, because it doesn't look at the right place.
However I have no clue what the problem could be, since you apparently have the correct setup. I suppose you will need to do some digging (printing variables, ideally of the state machine) on your own.
I've unfortunately ignored your friend request on discord, since I didn't know who you were. Please send it again, and we can chat over there so we don't spam this issue here. Once we solve the problem we can post our findings here.

**Comment by E7t7t7** [comment] 2023-08-17 05:57
i resent the friend request pengy1 or penguin photo is a penguin

**Comment by MOj0** [comment] 2023-08-18 18:10
Fixed by setting the window borderless.

**Closed as completed by MOj0** 2023-08-18 18:10 UTC
